import Head from "next/head";
import Image from "next/image";
import AdvanceStats from "../components/AdvanceStats/AdvanceStats";
import BYLToday from "../components/BoostYourLinkToday/BYLToday";
import HeroPage from "../components/HeroPage/HeroPage";
import UrlShortner from "../components/UrlShortner/UrlShortner";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroPage />

      <UrlShortner />
      <AdvanceStats />
      <BYLToday />
    </div>
  );
}
